plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrlaloo.tapomonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrlaloo.tapomonitor'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.6.1'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.6.1'
    implementation 'androidx.media3:media3-ui:1.6.1'
}
