plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrlaloo.tapomonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrlaloo.tapomonitor'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1-reconnect'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.6.1'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.6.1'
    implementation 'androidx.media3:media3-ui:1.6.1'
}
